export enum StaticTypeSPED {
    SpedInAjIcm = 'SpedInAjIcm',
    SpedInAjusteIpi = 'SpedInAjusteIpi',
    SpedInNatBc = 'SpedInNatBc',
    SpedInCenqIpi = 'SpedInCenqIpi',
    SpedInCfop = 'SpedInCfop',
    SpedInCodAjuste = 'SpedInCodAjuste',
    SpedInDispAutor = 'SpedInDispAutor',
    SpedInEnquadIpi = 'SpedInEnquadIpi',
    SpedInMotInv = 'SpedInMotInv',
    SpedInNatExp = 'SpedInNatExp',
    SpedInSeloIpi = 'SpedInSeloIpi',
    SpedInTotRedZ = 'SpedInTotRedZ',
    SpedInTpAjuste = 'SpedInTpAjuste',
    SpedInDocIcm = 'SpedInDocIcm',
    SpedInEmitente = 'SpedInEmitente',
    SpedInGenItem = 'SpedInGenItem',
    SpedInSitDocC = 'SpedInSitDocC',
    SpedInTabela = 'SpedInTabela',
    SpedInTipoItem = 'SpedInTipoItem'
}
